#
# Azure Pipelines build configuration for fluentd on Linux, macOS, and Windows
# 

trigger:
- master
- v0.12
- v0.14

jobs:
- job: Linux
  strategy:
    matrix:
      ruby_26:
        RUBY_VERSION: 2.6.2
      ruby_25:
        RUBY_VERSION: 2.5.5
      ruby_24:
        RUBY_VERSION: 2.4.6
      ruby_22:
        RUBY_VERSION: 2.2.10
      ruby_21:
        RUBY_VERSION: 2.1.10
      # TODO: use RVM to install ruby-head (unless there is an appropriate Docker image that can be used)
      # ruby_head:
      #   IMAGE: ''
  container: $[ format('ruby:{0}', variables.RUBY_VERSION) ]
  steps:
  - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  strategy:
    matrix:
      ruby_26:
        RUBY_VERSION: '>=2.6'
      ruby_24:
        RUBY_VERSION: 2.4.6
        USE_RVM: true
      ruby_21:
        RUBY_VERSION: 2.1.10
        USE_RVM: true
      ruby_head:
        RUBY_VERSION: head
        USE_RVM: true
  variables:
    RUBY_BINARIES_URL: https://fluentdazp.blob.core.windows.net/binaries/osx/10.13/x86_64/
  steps:
  # Note: we are currently using RVM to install Ruby, but this is *really* slow since it must compile source for the versions we need
  # We should switch to the UseRubyVersion task once the hosted macOS images supports the required versions
  - bash: |
      # Install RVM
      curl -sSL https://get.rvm.io | bash -s stable
      source ~/.rvm/scripts/rvm

      # Install Ruby pre-reqs
      rvm requirements

      # Download Ruby binary and install it      
      mkdir -p ~/rvm_binaries
      curl ${RUBY_BINARIES_URL}/${RUBY_VERSION}.tar.bz2 -o ~/rvm_binaries/ruby-${RUBY_VERSION}.tar.bz2
      rvm mount ~/rvm_binaries/ruby-${RUBY_VERSION}.tar.bz2
      rvm use ruby-${RUBY_VERSION}      
      # Propagate variables set by RVM (so they are available in later build steps). Needed since shell is launched with --no-profile/--no-rc
      echo "##vso[task.setvariable variable=PATH]$PATH"
      echo "##vso[task.setvariable variable=GEM_PATH]$GEM_PATH"
      echo "##vso[task.setvariable variable=GEM_HOME]$GEM_HOME"
    displayName: Install Ruby (via rvm)
    condition: variables.USE_RVM

  # TODO. See note above and https://github.com/Microsoft/azure-pipelines-image-generation/issues/834
  #
  #- task: UseRubyVersion@0
  #  inputs:
  #    versionSpec: '$(RUBY_VERSION)'
  #  displayName: Install Ruby
  #  condition: variables.SKIP_RVM

  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      # TODO: AppVeyor is currently building on 2.2 and 2.3 (and both x86 and x64) --- should we?
      ruby_24:
        RUBY_VERSION: 2.4.x
      ruby_25:
        RUBY_VERSION: 2.5.x
      ruby_25_rapid:
        RUBY_VERSION: 2.5.x
        WIN_RAPID: true
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '$(RUBY_VERSION)'
    displayName: Install Ruby

  - template: azure-pipelines-steps.yml