#
# Azure Pipelines build configuration for fluentd on Linux, macOS, and Windows
#
# Notes:
#  1. Currently using RVM to install Ruby on macOS. We should switch to the built-in task when available. See https://github.com/Microsoft/azure-pipelines-image-generation/issues/834
#  2. AppVeyor currently builds with Ruby 2.2 and 2.3 (both x86 and x64) --- should we do the same?
#  3. Currently not building against ruby-head on Linux.

trigger:
- master
- v0.12
- v0.14

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      ruby_26:
        RUBY_IMAGE: ruby:2.6.2        
      ruby_25:
        RUBY_IMAGE: ruby:2.5.5
      ruby_24:
        RUBY_IMAGE: ruby:2.4.6
      ruby_22:
        RUBY_IMAGE: ruby:2.2.10
        BUNDLER_VERSION: 1.17.3
      ruby_21:
        RUBY_IMAGE: ruby:2.1.10
        BUNDLER_VERSION: 1.17.3
      #ruby_head:
      #  RUBY_IMAGE: ruby:latest
      #  RUBY_VERSION: ruby-head
      #  USE_RVM: true
  container: $[ variables.RUBY_IMAGE ]
  steps:
  - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  strategy:
    matrix:
      ruby_26:
        RUBY_VERSION: 2.6.x
      ruby_24:
        RUBY_VERSION: 2.4.6
        USE_RVM: true
      ruby_21:
        RUBY_VERSION: 2.1.10
        BUNDLER_VERSION: 1.17.3
        USE_RVM: true
      ruby_head:
        RUBY_VERSION: ruby-head
        USE_RVM: true
  steps:
  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:      
      ruby_24:
        RUBY_VERSION: 2.4.x
        USE_HOSTED_TOOL: true
      ruby_25:
        RUBY_VERSION: 2.5.x
        USE_HOSTED_TOOL: true
      ruby_25_rapid:
        RUBY_VERSION: 2.5.x
        WIN_RAPID: true
        USE_HOSTED_TOOL: true
  steps:
  - template: azure-pipelines-steps.yml
