steps:
- script: |
    ruby --version
    bundle --version
    gem --version
  displayName: Show versions
    
- script: bundle install --retry=3 --jobs=4
  displayName: Install gems

- script: bundle exec rake test TESTOPTS=-v
  displayName: Test

# TODO: there was an issue publishing JUnit test reports (Value was either too large or too small for an Int32.). Need to investigate.
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'test/reports/*.xml' 
#     mergeTestResults: true
#     testRunTitle: '$(Agent.JobName)'
#     publishRunAttachments: true
#   condition: variables.WIN_RAPID
