#
# Azure Pipelines build configuration for fluentd on Linux, macOS, and Windows
# 

trigger:
- master
- v0.12
- v0.14

jobs:
- job: Linux
  strategy:
    matrix:
      ruby_26:
        IMAGE: ruby:2.6.2
      ruby_25:
        IMAGE: ruby:2.5.5
      ruby_24:
        IMAGE: ruby:2.4.6
      ruby_22:
        IMAGE: ruby:2.2.10
      ruby_21:
        IMAGE: ruby:2.1.10
      # TODO: use RVM to install ruby-head (unless there is an appropriate Docker image that can be used)
      # ruby_head:
      #   IMAGE: ''
  container: $[ variables.IMAGE ]
  steps:
  # Note: this is needed to avoid issues with StatWatcher not notifying on file changes
  - bash: |
      mkdir -p /dev/shm/tmp
      ln -s /dev/shm/tmp ./test/tmp
    displayName: Initialize test/tmp
  - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  strategy:
    matrix:
      ruby_26:
        RUBY_VERSION: '>=2.6'
        SKIP_RVM: true
      ruby_24:
        RUBY_VERSION: 2.4.5
      ruby_21:
        RUBY_VERSION: 2.1.10
      ruby_head:
        RUBY_VERSION: ruby-head
  steps:
  # Note: we are currently using RVM to install Ruby, but this is *really* slow since it must compile source for the versions we need
  # We should switch to the UseRubyVersion task once the hosted macOS images supports the required versions
  - bash: |
      curl -sSL https://get.rvm.io | bash -s stable      
      source ~/.rvm/scripts/rvm
      rvm install $RUBY_VERSION --default
    displayName: Install Ruby (via rvm)
    condition: not(variables.SKIP_RVM)

  # TODO. See note above and https://github.com/Microsoft/azure-pipelines-image-generation/issues/834
  #
  #- task: UseRubyVersion@0
  #  inputs:
  #    versionSpec: '$(RUBY_VERSION)'
  #  displayName: Install Ruby
  #  condition: variables.SKIP_RVM

  # Note: this is needed to avoid permission problems in some tests
  - script: mkdir -p ./test/tmp
    displayName: Initialize test/tmp
  
  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      # TODO: AppVeyor is currently building on 2.2 and 2.3 (and both x86 and x64) --- should we?
      ruby_24:
        RUBY_VERSION: 2.4.x
      ruby_25:
        RUBY_VERSION: 2.5.x
      ruby_25_rapid:
        RUBY_VERSION: 2.5.x
        WIN_RAPID: true
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '$(RUBY_VERSION)'
    displayName: Install Ruby

  - script: gem install bundler
    displayName: Install bundler gem

  - template: azure-pipelines-steps.yml      
